"""
Generates a downloadable PDF report combining: user profile, diet/workout
plan, SQL analytics summary, forecast summary, and recent form-check results.

Uses ReportLab's Platypus layer (not raw canvas drawing) so it's a real
paginated document with tables, not just text dumped onto a page.
"""

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

from modules.database import get_user_by_id, get_latest_plan
from modules.analytics import get_weekly_adherence
from modules.forecasting import fit_and_forecast, get_forecast_summary


def generate_pdf_report(user_id, output_path):
    """Builds the PDF and writes it to output_path. Returns output_path.
    Sections that don't have enough data (e.g. forecast needs 14+ days)
    are skipped gracefully with a note, rather than crashing the whole report."""

    user = get_user_by_id(user_id)
    if not user:
        raise ValueError(f"No user found with user_id {user_id}")

    plan = get_latest_plan(user_id)

    styles = getSampleStyleSheet()
    title_style = styles["Heading1"]
    section_style = styles["Heading2"]
    body_style = styles["BodyText"]

    doc = SimpleDocTemplate(output_path, pagesize=letter)
    story = []

    # --- Title ---
    story.append(Paragraph(f"Fitness &amp; Diet Report - {user['name']}", title_style))
    story.append(Spacer(1, 12))
    story.append(Paragraph(
        f"Goal: {user['goal']} | Activity level: {user['activity_level']} | "
        f"Age: {user['age']} | Gender: {user['gender']}",
        body_style
    ))
    story.append(Spacer(1, 20))

    # --- Diet plan ---
    story.append(Paragraph("Diet Plan", section_style))
    if plan:
        diet_table_data = [
            ["Calorie Target", f"{plan['calorie_target']} kcal/day"],
            ["Protein", f"{plan['protein_target']} g"],
            ["Carbs", f"{plan['carb_target']} g"],
            ["Fat", f"{plan['fat_target']} g"],
        ]
        diet_table = Table(diet_table_data, colWidths=[150, 200])
        diet_table.setStyle(_default_table_style())
        story.append(diet_table)
    else:
        story.append(Paragraph("No plan generated yet.", body_style))
    story.append(Spacer(1, 20))

    # --- Workout split ---
    story.append(Paragraph("Weekly Workout Split", section_style))
    if plan and plan.get("workout_split"):
        workout_table_data = [["Day", "Type", "Sets x Reps", "Rest"]]
        for day, details in plan["workout_split"].items():
            if details["type"] == "rest":
                workout_table_data.append([day, "Rest", "-", "-"])
            else:
                workout_table_data.append([
                    day, details["type"],
                    f"{details['sets']}x{details['reps']}",
                    f"{details['rest_seconds']}s"
                ])
        workout_table = Table(workout_table_data, colWidths=[80, 90, 90, 60])
        workout_table.setStyle(_default_table_style(header=True))
        story.append(workout_table)
    else:
        story.append(Paragraph("No workout split available.", body_style))
    story.append(Spacer(1, 20))

    # --- Analytics summary ---
    story.append(Paragraph("Adherence Summary", section_style))
    try:
        adherence_df = get_weekly_adherence(user_id)
        if not adherence_df.empty:
            avg_adherence = round(adherence_df["adherence_pct"].mean(), 1)
            story.append(Paragraph(
                f"Average weekly adherence across {len(adherence_df)} logged weeks: {avg_adherence}%",
                body_style
            ))
        else:
            story.append(Paragraph("Not enough logged data yet for an adherence summary.", body_style))
    except Exception:
        story.append(Paragraph("Adherence data unavailable.", body_style))
    story.append(Spacer(1, 20))

    # --- Forecast summary ---
    story.append(Paragraph("Weight Trend Forecast", section_style))
    try:
        _, forecast = fit_and_forecast(user_id, periods_days=28)
        summary_text = get_forecast_summary(forecast)
        story.append(Paragraph(summary_text, body_style))
    except ValueError as e:
        # Raised by prepare_prophet_input when there's under 14 days of data
        story.append(Paragraph(f"Forecast not available yet: {e}", body_style))
    story.append(Spacer(1, 20))

    # --- Footer note ---
    story.append(Spacer(1, 30))
    story.append(Paragraph(
        "Generated by FitPlan AI. Forecasts are estimates based on historical trend "
        "and should not be treated as guarantees.",
        ParagraphStyle("footer", parent=body_style, fontSize=8, textColor=colors.grey)
    ))

    doc.build(story)
    return output_path


def _default_table_style(header=False):
    style_commands = [
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]
    if header:
        style_commands.append(("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2c3e50")))
        style_commands.append(("TEXTCOLOR", (0, 0), (-1, 0), colors.white))
        style_commands.append(("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"))
    return TableStyle(style_commands)